<a href="https://colab.research.google.com/github/VasaviLagishetty/MachineLearning/blob/master/Data%20Preprocessing/Data_Preprocessing_Tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
url = 'https://raw.githubusercontent.com/VasaviLagishetty/MachineLearning/master/Data%20Preprocessing/Data.csv'
dataset = pd.read_csv(url)
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data using IterativeImputer, KNNImputer, SimpleImputer

In [5]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imputer = IterativeImputer()
x[:,1:3]=imputer.fit_transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 67211.83259075659],
       ['France', 35.0, 58000.0],
       ['Spain', 29.90395304729354, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [6]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors = 2)
x[:,1:3] = imputer.fit_transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 67211.83259075659],
       ['France', 35.0, 58000.0],
       ['Spain', 29.90395304729354, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 67211.83259075659]
 ['France' 35.0 58000.0]
 ['Spain' 29.90395304729354 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [9]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 67211.83259075659]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 29.90395304729354 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [10]:
y = LabelEncoder().fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Feature Scaling

## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [13]:
print(x_train,y_train)
print(x_test,y_test)

[[0.0 0.0 1.0 29.90395304729354 52000.0]
 [0.0 1.0 0.0 40.0 67211.83259075659]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]] [0 1 0 0 1 1 0 1]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]] [0 1]


In [0]:
from sklearn.preprocessing import StandardScaler
x_train = StandardScaler().fit_transform(x_train)
x_test = StandardScaler().fit_transform(x_test)

In [15]:
print(x_train,y_train)
print(x_test,y_test)

[[-0.77459667 -0.57735027  1.29099445 -1.18297114 -1.11247734]
 [-0.77459667  1.73205081 -0.77459667  0.13178868  0.18663188]
 [ 1.29099445 -0.57735027 -0.77459667  0.65268951  0.59554727]
 [-0.77459667 -0.57735027  1.29099445 -0.12866174 -0.34386627]
 [-0.77459667 -0.57735027  1.29099445 -1.56113903 -1.45408227]
 [ 1.29099445 -0.57735027 -0.77459667  1.17359034  1.19335588]
 [-0.77459667  1.73205081 -0.77459667  1.43404076  1.53496081]
 [ 1.29099445 -0.57735027 -0.77459667 -0.51933737 -0.60006996]] [0 1 0 0 1 1 0 1]
[[-1.  1.  0. -1. -1.]
 [ 1. -1.  0.  1.  1.]] [0 1]
